events {}

http {
  upstream cms_backend {
    server server1:5000;
    server server2:5000;
  }

  server {
    listen 80;

    location /api/ {
      proxy_pass http://cms_backend;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /health {
      return 200 "Nginx load balancer is running";
      add_header Content-Type text/plain;
    }
  }
}
